"""Versioned metadata for deterministic agent and MCP security review rules.

These rules find source evidence; they are not claims of exploitability or compliance.
"""

RULESET_VERSION = "1.3.0"

_MCP = "https://modelcontextprotocol.io/docs/2026-07-28/tutorials/security/security_best_practices"
_OWASP = "https://genai.owasp.org/resource/owasp-genai-llm-top-10-2026/"
_CISA = "https://www.cisa.gov/resources-tools/resources/secure-by-design"
_PYTHON = "https://docs.python.org/3/library/security_warnings.html"


def _rule(id, title, severity, category, description, remediation, cwe, references=None):
    return dict(id=id, title=title, severity=severity, category=category,
                description=description, remediation=remediation,
                cwe=cwe, references=references or [_OWASP, _CISA])


RULES = [
    _rule("AI001", "Dynamic Python code execution", "high", "tool_execution",
          "eval or exec receives a nonliteral expression. If agent, user, or tool content can reach it, it can execute arbitrary Python. Static analysis does not establish the full data flow.",
          "Replace dynamic execution with an allowlisted operation dispatcher; use ast.literal_eval only for bounded literal parsing. Isolate unavoidable execution with no ambient credentials and strict resource limits.", ["CWE-95"], [_PYTHON, _OWASP]),
    _rule("AI002", "Dynamic command executed through a shell", "high", "tool_execution",
          "A subprocess call enables a shell, invokes a shell-specific API, or passes a dynamic command to an explicit shell executable. Shell metacharacters in agent or external input may become executable syntax.",
          "Pass an argument list with shell=False, allowlist executable names and options, and enforce working-directory and resource restrictions.", ["CWE-78"], [_PYTHON, _OWASP]),
    _rule("AI003", "Dynamic os shell command", "high", "tool_execution",
          "os.system or os.popen executes a dynamically constructed command through the shell. Review the command's trust boundary.",
          "Use subprocess with a fixed executable and argument list, shell=False, and explicit allowed options.", ["CWE-78"], [_PYTHON, _OWASP]),
    _rule("AI004", "Unsafe YAML object construction", "high", "deserialization",
          "YAML is loaded through an unsafe loader or without an explicitly safe loader. Older or unsafe loaders can construct Python objects from input.",
          "Use yaml.safe_load or SafeLoader/CSafeLoader and validate the parsed schema and size.", ["CWE-502"], ["https://pyyaml.org/wiki/PyYAMLDocumentation"]),
    _rule("AI005", "Executable deserialization requires trusted inputs", "high", "deserialization",
          "Pickle-compatible deserialization can execute code. This finding identifies a dangerous trust boundary, not proof that the serialized input is attacker controlled.",
          "Use a nonexecutable serialization format with schema validation. If compatibility requires pickle, accept only authenticated artifacts from a strictly controlled producer.", ["CWE-502"], [_PYTHON]),
    _rule("AI006", "TLS certificate verification disabled", "high", "transport_security",
          "Certificate verification is explicitly disabled. A network intermediary may impersonate the remote service and capture prompts, credentials, or tool results.",
          "Enable certificate verification and install the correct CA bundle; use a trusted private CA for custom gateways.", ["CWE-295"], [_MCP, _CISA]),
    _rule("AI007", "Wildcard cross-origin access", "medium", "network_exposure",
          "Cross-origin access explicitly permits every origin. For credential-bearing or local MCP services this can expose a browser-accessible trust boundary; reachability and framework behavior require review.",
          "Allow only required origins, validate Origin on HTTP MCP endpoints, and combine origin checks with authentication. Do not combine wildcard origins with credentials.", ["CWE-942"], [_MCP]),
    _rule("AI008", "Service binds to all network interfaces", "low", "network_exposure",
          "A server explicitly binds to a wildcard address. This is a deployment review signal: source alone cannot establish actual network reachability or authentication.",
          "Bind local-only tools to loopback. For intentional remote services, verify ingress policy, TLS, authentication, and origin validation.", ["CWE-668"], [_MCP, _CISA]),
    _rule("AI009", "Application debug mode enabled", "medium", "configuration",
          "Debug mode is explicitly enabled in server code or configuration. Depending on the framework and deployment, error details or a debugger may become externally accessible.",
          "Disable debug mode in deployed services and return sanitized errors while retaining protected server-side diagnostics.", ["CWE-489"], [_CISA]),
    _rule("AI010", "Credential-like literal in source or configuration", "high", "secrets",
          "A credential-named field contains a nonplaceholder literal. It may be a real secret or test data; validate it without disclosing the value.",
          "If real, revoke and rotate the credential, remove it from source and history, and load it from a secret manager or environment variable with least privilege.", ["CWE-798"], [_CISA, _MCP]),
    _rule("AI011", "Private key material in repository", "critical", "secrets",
          "A private-key PEM header is followed by plausible encoded key material. Test keys may be intentional; this pattern does not prove cryptographic validity or production use.",
          "Determine whether the key was used, revoke or rotate it if necessary, remove it from version history, and use a managed key store.", ["CWE-321"], [_CISA]),
    _rule("AI012", "Dynamic JavaScript shell execution", "high", "tool_execution",
          "A Node child-process shell execution API receives a dynamic command. Agent or external content reaching this value may inject shell syntax.",
          "Use execFile or spawn with a fixed executable, validated argument array, and shell disabled; constrain tools by policy before execution.", ["CWE-78"], ["https://nodejs.org/api/child_process.html", _OWASP]),
    _rule("AI013", "Dynamic JavaScript code execution", "high", "tool_execution",
          "eval or the Function constructor evaluates a dynamic value as JavaScript. Review whether user, agent, or tool data can cross this execution boundary.",
          "Use validated structured data and allowlisted operations instead of evaluating generated code.", ["CWE-95"], [_OWASP]),
    _rule("AI014", "Externally influenced outbound request", "medium", "ssrf",
          "An outbound request uses an obvious external-input expression. This is a review signal for SSRF; this local analysis cannot prove whether upstream URL validation exists.",
          "Allowlist destinations and schemes, resolve and validate addresses on each connection and redirect, block metadata/private destinations unless explicitly needed, and enforce egress policy.", ["CWE-918"], [_MCP]),
    _rule("AI015", "Externally influenced filesystem path", "medium", "filesystem",
          "A filesystem operation consumes an obvious external-input expression. Review whether canonical path checks and symlink handling confine access to the intended workspace.",
          "Resolve paths under a fixed workspace root, reject paths outside it after canonicalization, handle symlinks safely, and give the process only required filesystem permissions.", ["CWE-22"], [_MCP, _OWASP]),
    _rule("AI016", "Race-prone temporary filename creation", "medium", "filesystem",
          "tempfile.mktemp returns an unused name without atomically creating the file, allowing a race with another local process.",
          "Use TemporaryFile, NamedTemporaryFile, TemporaryDirectory, or mkstemp with restrictive permissions and reliable cleanup.", ["CWE-377"], [_PYTHON]),
    _rule("AI017", "JWT verification explicitly bypassed", "high", "authentication",
          "JWT decoding explicitly disables signature verification or selects the none algorithm. Unverified claims must never authorize agent or MCP operations.",
          "Verify signature, algorithm allowlist, issuer, audience, expiry, and scopes before using claims for authorization.", ["CWE-347"], [_MCP]),
    _rule("AI018", "MCP package runner resolves an unpinned artifact", "medium", "supply_chain",
          "An MCP launch configuration uses npx, uvx, or a similar ephemeral package runner without an exact package version. The executable artifact can change between launches.",
          "Pin an exact audited package version and lock or verify transitive artifacts. Prefer preinstalled verified tools in a controlled environment.", ["CWE-829"], [_MCP, _CISA]),
    _rule("AI019", "Remote download piped directly to a shell", "high", "supply_chain",
          "Downloaded content is directly piped to a shell. A changed or compromised remote artifact becomes executable without a visible integrity check.",
          "Fetch a versioned artifact, verify an independently trusted digest or signature, review it, and execute it under least privilege.", ["CWE-829"], [_CISA]),
    _rule("AI020", "GitHub Action reference is not pinned to a commit", "medium", "supply_chain",
          "A remote GitHub Action is referenced using a mutable tag, branch, or noncommit reference. Its code can change without a workflow diff.",
          "Pin remote actions to a reviewed full commit SHA and use dependency automation to propose updates.", ["CWE-829"], ["https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions"]),
    _rule("AI021", "Container explicitly runs as root", "medium", "sandboxing",
          "The default final Dockerfile stage explicitly selects or inherits a literal root user. Build-target selection, external image defaults, variable expansion and runtime overrides require separate validation.",
          "Use a dedicated nonroot runtime user and minimal capabilities; verify the final build stage and deployment security context.", ["CWE-250"], [_CISA]),
    _rule("AI022", "Privileged container or privilege escalation enabled", "high", "sandboxing",
          "Container configuration explicitly enables privileged execution or privilege escalation, weakening isolation for tool or agent code.",
          "Disable privileged mode and privilege escalation, drop capabilities, and expose only narrowly required devices or operations.", ["CWE-250"], [_CISA]),
    _rule("AI023", "Container runtime socket exposed", "high", "sandboxing",
          "A container runtime socket is present in configuration. A writable Docker or containerd socket can give a tool control over host workloads.",
          "Remove runtime socket access or use a tightly scoped broker outside the agent sandbox. Read-only mounts do not necessarily make socket APIs read-only.", ["CWE-250"], [_CISA]),
    _rule("AI024", "Container image is not digest pinned", "low", "supply_chain",
          "A container base or deployment image uses a mutable reference rather than a content digest. The bytes can change between builds or deployments.",
          "Pin approved image digests, track provenance and SBOMs, and update through reviewed vulnerability-remediation workflows.", ["CWE-829"], [_CISA]),
    _rule("AI025", "Direct dependency is not exactly pinned", "low", "supply_chain",
          "A direct dependency declaration allows version movement. A lockfile elsewhere may constrain the actual installation; review the effective build process.",
          "Use a committed verified lockfile or exact pins and hashes, scan dependencies for known vulnerabilities, and review updates.", ["CWE-1104"], [_CISA]),
    _rule("AI026", "Authentication explicitly disabled", "high", "authentication",
          "An MCP or server configuration explicitly disables an authentication-related control. Local stdio servers may rely on an operating-system boundary; assess the actual transport and exposure.",
          "For remote protected resources, require authenticated clients and scoped per-tool authorization. Document local-only trust boundaries and protect launch configuration.", ["CWE-306"], [_MCP]),
    _rule("AI027", "Wildcard tool or permission authorization", "high", "authorization",
          "An authorization or tool allowlist explicitly grants a wildcard or all-tools capability. This may give an agent broader authority than its task requires.",
          "Replace wildcard grants with named tools and constrained resources; enforce authorization server-side for each call and require approval for sensitive effects.", ["CWE-732"], [_MCP, _OWASP]),
    _rule("AI028", "MCP token passthrough enabled", "high", "authentication",
          "Configuration explicitly enables token passthrough or token forwarding. Forwarding an inbound token to an unrelated downstream audience can bypass consent and authorization boundaries.",
          "Validate tokens for this MCP resource and obtain separate audience-bound downstream credentials through an appropriate authorization flow.", ["CWE-441"], [_MCP]),
    _rule("AI029", "Remote MCP URL uses plaintext HTTP", "high", "transport_security",
          "An MCP configuration points to a nonloopback HTTP URL. Credentials, tool requests, and results may be exposed in transit; network-layer protection is not established by this scan.",
          "Use HTTPS with certificate verification for remote MCP endpoints. Reserve plaintext HTTP for explicitly controlled local development or a documented protected transport.", ["CWE-319"], [_MCP]),
    _rule("AI030", "Browser-side API credential access explicitly enabled", "medium", "secrets",
          "An SDK explicitly enables browser execution despite credential-exposure safeguards. Verify that a durable privileged API key cannot reach client-side code.",
          "Keep durable API credentials on a trusted server, or use narrowly scoped short-lived client tokens designed for the browser.", ["CWE-522"], [_CISA]),
    _rule("AI031", "Agent approval or sandbox safeguard explicitly bypassed", "high", "agent_permissions",
          "An agent configuration or command explicitly disables approvals or enables unrestricted execution. The impact depends on the process identity, tools, and sandbox.",
          "Use bounded tool permissions and an isolated runtime; require deliberate approval for destructive, external, financial, or credential-bearing actions.", ["CWE-862"], [_OWASP, _MCP]),
    _rule("AI032", "External data inserted into privileged LLM instructions", "medium", "prompt_injection",
          "A system or developer message contains an obvious external-input expression. Untrusted data may be interpreted as privileged instructions; local analysis cannot establish exploitability.",
          "Keep trusted instructions separate from untrusted content, label provenance, enforce tool policy outside the model, and test indirect prompt injection and sensitive-action approval.", ["CWE-1427"], [_OWASP]),
    _rule("AI033", "Potential secret included in logging call", "medium", "data_protection",
          "A logging call directly references a credential-named variable or field. Log processors and retention can broaden access to secrets.",
          "Log nonsecret identifiers and outcomes; redact credentials before formatting and restrict log access and retention.", ["CWE-532"], [_CISA]),
    _rule("AI034", "Credential-like value embedded in URL query", "high", "data_protection",
          "A URL contains a credential-like query parameter with a nonplaceholder value. URLs can be retained in logs, histories, proxies, and telemetry.",
          "Use an appropriate authorization header or short-lived scoped credential; redact existing logs and rotate real exposed credentials.", ["CWE-598"], [_MCP]),
    _rule("AI035", "Unsafe model checkpoint deserialization", "high", "model_supply_chain",
          "torch.load explicitly sets weights_only=False or a framework disables safe model loading. An untrusted artifact may contain executable object deserialization.",
          "Use safe tensor formats or restricted weights-only loading, verify model provenance and integrity, and isolate model conversion workflows.", ["CWE-502"], ["https://pytorch.org/docs/stable/notes/serialization.html", _CISA]),
    _rule("AI036", "SQL query constructed with interpolation", "high", "tool_execution",
          "A database execution call receives an interpolated or concatenated SQL expression. If untrusted content contributes, it may change the query's meaning.",
          "Use bound query parameters for values and an explicit allowlist for dynamic SQL identifiers or operations.", ["CWE-89"], [_CISA]),
    _rule("AI037", "Archive extraction without an explicit safe filter", "medium", "filesystem",
          "A tar extraction call has no explicit safe data filter, or selects a fully trusted filter. Behavior depends on the Python version and archive provenance.",
          "Use filter='data' on supported runtimes, validate members and resource limits, and extract into an isolated directory with no sensitive files.", ["CWE-22"], ["https://docs.python.org/3/library/tarfile.html#extraction-filters"]),
    _rule("AI038", "Cryptographically weak randomness used for a security value", "medium", "authentication",
          "A credential-, nonce-, or token-named assignment uses a general-purpose random generator. Predictability matters if the value protects access or replay prevention.",
          "Use the secrets module or a cryptographically secure runtime API with sufficient entropy for security values.", ["CWE-338"], [_PYTHON]),
    _rule("AI039", "Server-Side Template rendered from a dynamic template", "high", "tool_execution",
          "A server-side template string is dynamically supplied. If agent or user content controls template source, template expressions may execute with server privileges.",
          "Use a fixed trusted template and pass untrusted content only as escaped data; sandbox and limit any intentional template authoring.", ["CWE-1336"], [_CISA]),
    _rule("AI040", "Unsafe HTML rendering boundary", "medium", "output_handling",
          "Dynamic content is passed to an HTML rendering bypass. Agent or tool-generated content may contain executable browser markup if not sanitized.",
          "Render untrusted output as text or sanitize with a maintained HTML policy before using a raw-HTML sink; apply a restrictive content security policy.", ["CWE-79"], [_OWASP]),
    _rule("AI041", "MCP inspector authorization explicitly disabled", "high", "authentication",
          "The MCP inspector's authorization safeguard is explicitly disabled. A reachable inspector may provide access to connected tools and their privileges.",
          "Retain inspector authentication and restrict its listeners and origins to a controlled development environment.", ["CWE-306"], [_MCP]),
    _rule("AI042", "Container uses host namespaces", "high", "sandboxing",
          "Container configuration explicitly uses the host PID namespace or host networking. This weakens separation between agent tooling and the host.",
          "Use isolated namespaces and explicit network rules; document and minimize any unavoidable host-level access.", ["CWE-653"], [_CISA]),
]

RULE_BY_ID = {rule["id"]: rule for rule in RULES}
